import midi_parser
import random

class GCodeMachineException(Exception):
    pass

class MoveOutOfBounds(GCodeMachineException):
    def __init__(self, pos, dim):
        self.pos = pos
        self.dim = dim
        self.message = f"Machine out of bounds! Wanted to move to {pos}, but dimensions is {dim}"
        super().__init__(self.message)

HZ2FR = 3.033

def tone_to_g1(fq1, fq2, t):
    # fq1, fq2 in hertz, t in seconds
    # Gives (feedrate, dx, dy)

    fr1, fr2 = fq1 * HZ2FR, fq2 * HZ2FR

    dia_speed = (fr1 ** 2 + fr2 ** 2) ** 0.5

    t_min = t / 60

    return (dia_speed, fr1 * t_min, fr2 * t_min)


class GCodeMachine:
    def __init__(self, width, height):
        self.gcode = ""
        self.position = (0, 0)
        self.dimensions = (width, height)

    def setup(self):
        self.do_gcode("# Generated by laser-bells <github.com/loovjo/laser-bells>") # Absolute programming
        self.do_gcode("G90") # Absolute programming
        self.do_gcode("G21") # Millimeters
        self.do_gcode("G28") # Auto home

    def finalize(self):
        self.do_gcode("M02") # Done?

    def do_gcode(self, gcode_line):
        self.gcode += gcode_line + "\n"

    def move_to(self, fr, x, y):
        if 0 <= x < self.dimensions[0] and 0 <= y < self.dimensions[1]:
            self.do_gcode(f"G1 F{fr:.5f} X{x:.5f} Y{y:.5f}")
            self.position = (x, y)
        else:
            raise MoveOutOfBounds((x, y), self.dimensions)

    def tone(self, fq1, fq2, t):
        if fq1 == fq2 == 0:
            # delay
            if t > 1:
                self.do_gcode(f"G4 S{int(t)} P{int(1000*(t%1))}")
            else:
                self.do_gcode(f"G4 P{int(1000*(t%1))}")
            return

        fr, dx, dy = tone_to_g1(fq1, fq2, t)
        if random.random() < 0.5:
            dx, dy = dy, dx

        if self.position[0] > self.dimensions[0] / 2:
            dx *= -1

        if self.position[1] > self.dimensions[1] / 2:
            dy *= -1

        try:
            self.move_to(fr, self.position[0] + dx, self.position[1] + dy)
        except MoveOutOfBounds as e:
            if t < 0.01:
                print("At", self.position, "dxdy=", dx, dy)
                print(e)
                exit()
            else:
                self.tone(fq1, fq2, t / 2)
                self.tone(fq1, fq2, t / 2)

parsed = midi_parser.read_midi("MIDI-Samples/Jingle_Bells.mid")
print(parsed)

last_t = 0
melody = []
for i in range(len(parsed) - 1):
    melody.append((parsed[i][1], 0, parsed[i+1][0] - parsed[i][0]))

print(melody)

machine = GCodeMachine(375, 315)
machine.setup()

for fq1, fq2, t in melody:
    machine.tone(fq1, fq2, t)

machine.finalize()

print(machine.gcode)
